#!/bin/bash

while [ "1"="1" ]; do
    WORK1="0"
    for PID in $( pidof -s /home/pi/src/modbus/mbus.py ); do
	WORK1="1"
	echo "mbus - ok"
    done
    if [[ "$WORK1" = "0" ]]; then
	killall mbus.py
#	screen -dmS mbus sudo /home/pi/src/modbus/mbus.py
	sudo /home/pi/src/modbus/mbus.py &
	echo "mbus start"
    fi

    WORK2="0"
    for PID in $( pidof -s runserver ); do
        WORK2="1"
	echo "runserver ok"
    done
    if [[ "$WORK2" = "0" ]]; then
        killall runserver
#        screen -dmS django /usr/bin/python /home/pi/src/iface/iface/manage.py runserver 0.0.0.0:8000
#	screen -dmS django /usr/bin/runserver
	sudo /usr/bin/runserver &
	echo "runserver start"
    fi

    sleep 20
done
