# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramlog',
            fields=[
                ('idparamlog', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_id', models.IntegerField()),
                ('addr', models.IntegerField()),
                ('addr_type', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paramlog',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='parametrs',
            options={'managed': True},
        ),
    ]
