# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celse', '0002_auto_20160520_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrs',
            name='to_log',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrs',
            name='to_set',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametrs',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
